### ISSUE TITLE
IllegalStateException: Can't get window from the Context

### ISSUE THREAD

**Issue by Queatz** [akshay2211/DrawBox#51]
When I call `drawController.saveBitmap()` I get this error. Maybe because my DrawBox is in a Dialog?

```
java.lang.IllegalStateException: Can't get window from the Context
	at io.ak1.drawbox.HelperKt.drawBitmapFromView(Helper.kt:78)
	at io.ak1.drawbox.DrawController$trackBitmaps$$inlined$mapNotNull$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
```

**Comment by akshay2211** [comment]
@Queatz This has been fixed in the latest release. Please reopen if you experience any issues.
